config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'signup', to: 'users#new'
  get 'logout', to: 'sessions#destroy'
  resources :messages, only: %i[create index]

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 15 }
  has_secure_password
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    return if logged_in?

    flash[:error] = 'You must be logged in to perform that action'
    redirect_to login_path
  end
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  def index
    redirect_to login_path unless logged_in?
    @message = Message.new
    @messages = Message.all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user, only: [:create]
  def create
    @message = Message.new(message_params)
    @message.user = current_user
    return unless @message.save

    redirect_to root_path

    # return unless @message.save

    # ActionCable.server.broadcast 'chatroom_channel',
    #                              foo: message_render(@message)
  end

  private

    def message_params
      params.require(:message).permit(:description)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :find_user, only: [:create]
  def new; end

  def create
    if @user&.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_url
      flash[:notice] = 'Logged in!'
    else
      flash[:alert] = 'Invalid username or password'
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash.now[:success] = 'Logged out!'
    redirect_to root_url
  end

  def find_user
    @user = User.find_by(username: params[:username])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  att_accessor :username, :password
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatroom/index.html.erb
<section class="bg-neutral-50 px-6 py-10 text-center text-neutral-800 dark:bg-neutral-700 dark:text-neutral-200 flex flex-col items-center ">
  <h1 class="mb-6 text-5xl font-bold">Coffee chat time</h1>
  <h3 class="mb-8 text-3xl font-bold">Welcome to chatRoom</h3>
</section>

<section class="grid grid-cols-6 gap-4 py-4 px-4">
  <div class="col-span-4 border border-gary-300 pl-2">
    <div class="h-40">
      <%= render template: 'messages/index' %>
    </div>
      <%= form_with(model: @message, url: messages_path) do |form| %>
        <div class="grid grid-cols-12 gap-4 w-full">

          <%= form.text_field :description, required: true, class: "col-span-9 h-8" %>

          <%= form.submit "Send", class: "col-span-2 bg-orange-400 px-8 h-8" %>
        </div>
      <% end %>

    <div class="mt-6">extra content, input section</div>
  </div>
  <div class="col-span-2 border border-gary-300 pl-2">user section</div>
</section>

app/views/layouts/_messages.html.erb
<% flash.each do |type, msg| %>
  <% if type== 'alert' %>
    <div class="text-red-500">
      <%= msg %>
    </div>
  <% else %>
    <div class="text-lime-500">
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-800">
  <div class="container flex flex-wrap justify-between items-center mx-auto">

    <span ><%= link_to 'ChatRoom', root_path, class: "self-start text-xl font-semibold whitespace-nowrap dark:text-white text-white"%></span>

    <div class="hidden w-full md:block md:w-auto" id="mobile-menu">
      <ul class="flex flex-col mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium">
        <li>
          <span class="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">
            <% if logged_in? %>
              <span>Username: </span><%= current_user.username %>
            <% else %>
              <%= link_to 'Login or Sign Up', login_path%>
            <% end %>
            </span>
        </li>
        <li>
          <span class="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">
            <% if logged_in? %>
              <%= link_to 'Logout', logout_path %>
            <% else %>
              <span></span>
            <%end %>
            </span>
        </li>
        <li>
          <a href="#" class="block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Account</a>
        </li>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageApp</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", media: 'all', "data-turbo-track": "reload" %>


    <%= javascript_importmap_tags %>
  </head>

  <%= render 'layouts/navigation' %>
  <body class="container mx-auto">
      <%= render 'layouts/messages' %>
      <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<% @messages.each do |message| %>
  <div class="flex flex-col gap-2 w-full">

    <p ><em class="font-semibold"><%= message.user.username  %></em> <span class="font-normal ">:<%= message.description %></span></p>

  </div>
<% end %>